### PR TITLE
Remove Search History references

### PR DESCRIPTION
**Pull request by slavkoder**
I am under impression that Search History part is redundant. Hopefully, removing it would help avoid confusion among students. Let me know if I'm wrong or if we want to add another section to lab exercises: https://courses.codepath.com/courses/android_university_fast_track/unit/3#!exercises

### CODE REVIEW

**Comment by rogerhu** [comment]
Just to clarify.. you mean it's not relevant to the assignment?

**Comment by slavkoder** [comment]
@rogerhu yeah, there is no mentioning of Search History on the assignment page. Also, no `SearchHistoryActivity` is present in the project.

**Comment by rogerhu** [comment]
I think that's probably the last debugging exercise I couldn't find!   I suspect it makes the Toolbar exercise a little bit more fun.

**Comment by rogerhu** [comment]
Never mind -- I nuked that exercise when the bug wasn't apparent.  Nuked the files in the upstream/branch.  Thanks!

**Pull request closed without merging**
